"""Generate the editable Jupyter notebook using only Python's standard library."""
import json
import hashlib
from pathlib import Path


def md(source):
    return {"cell_type": "markdown", "id": hashlib.sha1(source.encode()).hexdigest()[:12], "metadata": {}, "source": source.splitlines(True)}


def code(source):
    return {"cell_type": "code", "id": hashlib.sha1(source.encode()).hexdigest()[:12], "execution_count": None, "metadata": {}, "outputs": [], "source": source.splitlines(True)}


cells = [
    md("# Metro Manila AADT simulation, 2025–2035\n\nRun all cells from top to bottom. This is a **scenario forecast** of daily PCU demand relative to **synthetic, unmeasured capacity** for 20 roads. The Random Forest classifies risk; 4.5% annual growth generates the baseline traffic forecast. A deterministic V/C rule is retained as the reference classification."),
    md("## 1. Setup and data checks\n\nInstall packages from `requirements.txt` in your Jupyter environment. Open this notebook from the repository root so the relative dataset path works."),
    code("from pathlib import Path\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom aadt_model import (CLASSES, RISK_ORDER, RING_ROADS, validate_data, add_pcu_and_risk, risk_from_ratio, fit_and_evaluate, simulate, save_outputs)\n\nDATA_PATH = Path('data/metro_manila_aadt_simulation_input_2020_2025.csv')\nraw = pd.read_csv(DATA_PATH)\nhistory = add_pcu_and_risk(validate_data(raw))\nprint(f'{len(history)} historical rows; {history.Road_ID_Name.nunique()} roads; years {history.Year.min()}–{history.Year.max()}')\nprint('Road types:', history.Road_Type.value_counts().to_dict())\nprint('Largest absolute PCU recomputation difference:', history.PCU_Difference.abs().max())\nassert history.PCU_Difference.abs().max() < 1.0\ndisplay(history[['Year', 'Road_ID_Name', 'Road_Type', 'Road_PCU_Volume', 'Capacity_Limit', 'VC_Ratio', 'Rule_Risk_Level']].head())"),
    code("for col in ['AADT_Review_Status', 'PCEF_Profile_Status', 'Capacity_Status', 'Data_Flag']:\n    print(f'\\n{col}:')\n    display(history[col].value_counts(dropna=False))\nprint('2025 baseline risk counts:')\ndisplay(history.loc[history.Year.eq(2025), 'Rule_Risk_Level'].value_counts().reindex(RISK_ORDER, fill_value=0))"),
    md("## 2. Random Forest assessment\n\nTrain on 2020–2023 and evaluate on 2024–2025. The target is calculated from PCU/capacity, so this test measures how well the forest reproduces that rule, **not** independent forecasting skill. The direct threshold rule is exact by definition. Forests can also plateau beyond historical feature ranges."),
    code("model, metrics, confusion, comparison = fit_and_evaluate(history)\nprint('Training classes:', history.loc[history.Year.le(2023), 'Rule_Risk_Level'].value_counts().to_dict())\nprint('Holdout classes:', comparison.Rule_Risk_Level.value_counts().to_dict())\nprint('Random Forest holdout metrics:')\ndisplay(metrics)\nprint('Confusion matrix (actual rows, predicted columns):')\ndisplay(confusion)\nprint('Forest disagreements with the direct V/C rule:', int(comparison.Disagreement.sum()), 'of', len(comparison))\ndisplay(comparison.loc[comparison.Disagreement].head(20))"),
    md("## 3. Annual simulation\n\nThe 2025 rows are recorded unchanged. For 2026–2035, vehicle counts grow once per year and PCU is recalculated. Baseline capacity stays fixed. The transit scenario moves 20% of projected cars to public buses at an illustrative 40 shifted cars per additional bus; this is a sensitivity assumption, not an observed mode shift. The expansion scenario increases synthetic capacity by 20% on EDSA and C-5 from 2028."),
    code("baseline = simulate(history, model, 'Baseline 4.5%', growth_rate=0.045)\naccelerated = simulate(history, model, 'Accelerated 7%', growth_rate=0.07)\ntransit = simulate(history, model, 'Transit shift 20%', growth_rate=0.045, transfer_share=0.20)\nexpansion = simulate(history, model, 'EDSA/C-5 expansion 20%', growth_rate=0.045, capacity_increase=0.20)\nresults = pd.concat([baseline, accelerated, transit, expansion], ignore_index=True)\nprint('Rows by scenario:', results.groupby('Scenario').size().to_dict())\ndisplay(baseline[['Year', 'Road_ID_Name', 'Road_PCU_Volume', 'Capacity_Limit', 'VC_Ratio', 'Risk_Level', 'RF_Risk_Level', 'First_High_Year']].head(20))"),
    code("assert risk_from_ratio(0.6999) == 'Low'\nassert risk_from_ratio(0.70) == 'Medium'\nassert risk_from_ratio(0.95) == 'High'\nfor scenario, frame in results.groupby('Scenario'):\n    assert frame.groupby('Year').size().eq(20).all(), scenario\n    assert not frame.duplicated(['Year', 'Road_ID_Name']).any(), scenario\n    assert set(frame.Year) == set(range(2025, 2036)), scenario\nassert np.allclose(baseline.loc[baseline.Year.eq(2025), 'Road_PCU_Volume'].to_numpy(), history.loc[history.Year.eq(2025), 'Road_PCU_Volume'].to_numpy())\ncheck = baseline.pivot(index='Road_ID_Name', columns='Year', values='Car')\nassert np.allclose(check[2026], check[2025] * 1.045)\nassert np.allclose(check[2035], check[2025] * 1.045**10)\nassert baseline.groupby('Road_ID_Name').Capacity_Limit.nunique().eq(1).all()\nprint('Simulation checks passed.')"),
    md("## 4. Results\n\n`First_High_Year` means the first year that the *scenario V/C rule* reaches 0.95 within 2025–2035. A blank value means it did not cross during this horizon. It does not establish the year of physical failure."),
    code("summary = results.loc[results.Year.eq(2035), ['Scenario', 'Road_ID_Name', 'Road_Type', 'Road_PCU_Volume', 'Capacity_Limit', 'VC_Ratio', 'Risk_Level', 'RF_Risk_Level', 'First_High_Year']]\ndisplay(summary.sort_values(['Scenario', 'VC_Ratio'], ascending=[True, False]))\nrisk_counts = results.groupby(['Scenario', 'Year', 'Risk_Level']).size().unstack(fill_value=0).reindex(columns=RISK_ORDER, fill_value=0)\ndisplay(risk_counts)\nprint('RF/rule disagreement by scenario:', results.groupby('Scenario').RF_Disagreement.sum().to_dict())"),
    code("risk_numeric = baseline.pivot(index='Road_ID_Name', columns='Year', values='VC_Ratio')\nplt.figure(figsize=(13, 8))\nsns.heatmap(risk_numeric, cmap='YlOrRd', annot=True, fmt='.2f', cbar_kws={'label':'V/C ratio'})\nplt.title('Baseline V/C ratio by road and year — synthetic capacity')\nplt.tight_layout()\nplt.show()"),
    code("type_year = baseline.groupby(['Year', 'Road_Type'], as_index=False).VC_Ratio.median()\nplt.figure(figsize=(10, 5))\nsns.lineplot(data=type_year, x='Year', y='VC_Ratio', hue='Road_Type', marker='o')\nplt.axhline(0.70, ls='--', color='orange', label='Medium threshold')\nplt.axhline(0.95, ls='--', color='red', label='High threshold')\nplt.title('Median baseline V/C by road type — synthetic capacity')\nplt.ylabel('Median V/C ratio')\nplt.tight_layout()\nplt.show()"),
    code("save_outputs(results, Path('outputs'))\nprint('Saved outputs/road_year_forecast.csv and outputs/scenario_2035_summary.csv')"),
    md("## Interpretation limits\n\nAll supplied AADT source rows require verification, PCU factors are marked as project/literature assumptions, and capacity is explicitly synthetic. The model assumes uniform vehicle-class growth in its baseline; annual averages cannot describe rush-hour queues, incidents, flooding, or vehicle-level behavior. Different scenario results show sensitivity to assumptions, not a calibrated uncertainty interval. Human traffic planners should verify sources and capacity before using these results for decisions."),
]

notebook = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python"}}, "nbformat": 4, "nbformat_minor": 5}
Path("aadt_simulation_2025_2035.ipynb").write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
